### ISSUE TITLE
update README

### ISSUE THREAD

**Issue by poulomihore** [lugnitdgp/Linux-networking#2]
1. Just go through the commands and give a brief description in README.md file about what networking 
    is, how it is important in present day lives in the form of internet.
2.  **Follow the markdown format.** 
3. And better give a proper link to markdown documentation so that other users can follow it while 
    contributing on this repository.

**Comment by poulomihore** [comment]
Go through the commands and give a brief description of that in README.Also specify the format and discuss about it in brief.

**Comment by AnirbanBanik1998** [comment]
Updated Readme.md...check my pr
